#!/bin/bash
#@ job_name = test_algorithm3
#@ initialdir = .
#@ output = algorithm3_%j.out
#@ error = algorithm3_%j.err
#@ total_tasks = 1
#@ cpus_per_task = 15
#@ wall_clock_limit = 168:00:00
#@ class = long7
python2.7 algorithm3.py -t b
