#!/bin/bash
#@ job_name = test_algorithm2
#@ initialdir = .
#@ output = algorithm2_%j.out
#@ error = algorithm2_%j.err
#@ total_tasks = 1
#@ cpus_per_task = 15
#@ wall_clock_limit = 168:00:00
#@ class = long7
python2.7 algorithm2.py -t b
